In [52]:
# import necessary packages
import numpy as np
import pandas as pd
import string
import re
import nltk
from nltk.tokenize import word_tokenize, sent_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\24746\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\24746\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\24746\AppData\Roaming\nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [53]:
# read data
data = pd.read_csv('data/spam.csv', encoding='ISO-8859-1')

# drop extra column
data = data.dropna(how="any", axis=1)
data.columns = ['label', 'text']

data = data.dropna(how="any", axis=1)

In [54]:
data

label                                               text
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...
...    ...                                                ...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham              Will Ì_ b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [55]:
data['text'] = data['text'].apply(lambda s: s.lower()).str.strip()
data['text'] = data['text'].apply(lambda s: s.translate(str.maketrans(string.whitespace, ' '*len(string.whitespace),'')))
data['text'] = data['text'].drop_duplicates()
# replace non alphabeths with spaces, and collapse spaces
data['text'] = data['text'].replace(r'[^A-Za-z\d]', ' ', regex=True)
data['text'] = data['text'].replace(r'\s+', ' ', regex=True)

In [56]:
# message length
data['length'] = data['text'].astype(str).apply(lambda x: len(x.split(' '))-1)
data.head()

label                                               text  length
0   ham  go until jurong point crazy available only in ...      20
1   ham                           ok lar joking wif u oni        6
2  spam  free entry in 2 a wkly comp to win fa cup fina...      32
3   ham       u dun say so early hor u c already then say       11
4   ham  nah i don t think he goes to usf he lives arou...      13

In [57]:
# tokenization
data['sentence'] = data['text'].astype(str).map(sent_tokenize)

data['words'] = data['sentence'].apply(lambda sentences: [word_tokenize(sentence) for sentence in sentences])
data['words_cleaned'] = data['words'].apply(lambda word_lists: [word for sublist in word_lists for word in sublist if word.isalnum()])

# remove stop words
stop_words = set(stopwords.words('english'))
words_cleaned = data['words_cleaned']

new_filtered_words = [word for word in words_cleaned if word not in stopwords.words('english')]

# emoticons, symbols
emoticon_pattern = re.compile("["  
    u"\U0001F600-\U0001F64F"  # emoticons
    u"\U0001F300-\U0001F5FF"  # symbols & pictographs
    u"\U0001F680-\U0001F6FF"  # transport & map symbols
    u"\U0001F1E0-\U0001F1FF"  # flags (iOS)
    u"\U00002500-\U00002BEF"  # Chinese characters
    u"\U00002702-\U000027B0"
    "]+", flags=re.UNICODE)

data = data.replace(emoticon_pattern, '', regex=True)

# remove extra columns which save tokenized sent and word
# data = data.drop(['words','sentence'], axis=1) 

# stemming
ps = PorterStemmer()
data['stemmed_words'] = data['words_cleaned'].map(lambda words: [ps.stem(word) for word in words])

# lemmatization
lemmatizer = WordNetLemmatizer()
data['lemmatized_words'] = data['words_cleaned'].map(lambda words: [lemmatizer.lemmatize(word) for word in words])

data.to_csv('data/results.csv', index=False)
data

label                                               text  length  \
0      ham  go until jurong point crazy available only in ...      20   
1      ham                           ok lar joking wif u oni        6   
2     spam  free entry in 2 a wkly comp to win fa cup fina...      32   
3      ham       u dun say so early hor u c already then say       11   
4      ham  nah i don t think he goes to usf he lives arou...      13   
...    ...                                                ...     ...   
5567  spam  this is the 2nd time we have tried 2 contact u...      32   
5568   ham                 will b going to esplanade fr home        7   
5569   ham  pity was in mood for that so any other suggest...      10   
5570   ham  the guy did some bitching but i acted like i d...      26   
5571   ham                          rofl its true to its name       5   

                                               sentence  \
0     [go until jurong point crazy available only in...   
1                             [ok lar joking wif u oni]   
2     [free entry in 2 a wkly comp to win fa cup fin...   
3         [u dun say so early hor u c already then say]   
4     [nah i don t think he goes to usf he lives aro...   
...                                                 ...   
5567  [this is the 2nd time we have tried 2 contact ...   
5568                [will b going to esplanade fr home]   
5569  [pity was in mood for that so any other sugges...   
5570  [the guy did some bitching but i acted like i ...   
5571                        [rofl its true to its name]   

                                                  words  \
0     [[go, until, jurong, point, crazy, available, ...   
1                      [[ok, lar, joking, wif, u, oni]]   
2     [[free, entry, in, 2, a, wkly, comp, to, win, ...   
3     [[u, dun, say, so, early, hor, u, c, already, ...   
4     [[nah, i, don, t, think, he, goes, to, usf, he...   
...                                                 ...   
5567  [[this, is, the, 2nd, time, we, have, tried, 2...   
5568        [[will, b, going, to, esplanade, fr, home]]   
5569  [[pity, was, in, mood, for, that, so, any, oth...   
5570  [[the, guy, did, some, bitching, but, i, acted...   
5571                 [[rofl, its, true, to, its, name]]   

                                          words_cleaned  \
0     [go, until, jurong, point, crazy, available, o...   
1                        [ok, lar, joking, wif, u, oni]   
2     [free, entry, in, 2, a, wkly, comp, to, win, f...   
3     [u, dun, say, so, early, hor, u, c, already, t...   
4     [nah, i, don, t, think, he, goes, to, usf, he,...   
...                                                 ...   
5567  [this, is, the, 2nd, time, we, have, tried, 2,...   
5568          [will, b, going, to, esplanade, fr, home]   
5569  [pity, was, in, mood, for, that, so, any, othe...   
5570  [the, guy, did, some, bitching, but, i, acted,...   
5571                   [rofl, its, true, to, its, name]   

                                          stemmed_words  \
0     [go, until, jurong, point, crazi, avail, onli,...   
1                          [ok, lar, joke, wif, u, oni]   
2     [free, entri, in, 2, a, wkli, comp, to, win, f...   
3     [u, dun, say, so, earli, hor, u, c, alreadi, t...   
4     [nah, i, don, t, think, he, goe, to, usf, he, ...   
...                                                 ...   
5567  [thi, is, the, 2nd, time, we, have, tri, 2, co...   
5568              [will, b, go, to, esplanad, fr, home]   
5569  [piti, wa, in, mood, for, that, so, ani, other...   
5570  [the, guy, did, some, bitch, but, i, act, like...   
5571                     [rofl, it, true, to, it, name]   

                                       lemmatized_words  
0     [go, until, jurong, point, crazy, available, o...  
1                        [ok, lar, joking, wif, u, oni]  
2     [free, entry, in, 2, a, wkly, comp, to, win, f...  
3     [u, dun, say, so, early, hor, u, c, already, t...  
4 

In [58]:
data['text2'] = pd.Series([
    'Todays Voda numbers ending 1225 are selected to receive a å£50award. \'',
    '     If you have a match please call 08712300220 quoting claim code 3100 standard rates app")',
    'todays voda numbers ending selected receive award match quoting claim code standard rates app'
    ])

# remove extra columns which save tokenized sent and word
data = data.drop(['words','sentence','stemmed_words', 'lemmatized_words'], axis=1) 
data

label                                               text  length  \
0      ham  go until jurong point crazy available only in ...      20   
1      ham                           ok lar joking wif u oni        6   
2     spam  free entry in 2 a wkly comp to win fa cup fina...      32   
3      ham       u dun say so early hor u c already then say       11   
4      ham  nah i don t think he goes to usf he lives arou...      13   
...    ...                                                ...     ...   
5567  spam  this is the 2nd time we have tried 2 contact u...      32   
5568   ham                 will b going to esplanade fr home        7   
5569   ham  pity was in mood for that so any other suggest...      10   
5570   ham  the guy did some bitching but i acted like i d...      26   
5571   ham                          rofl its true to its name       5   

                                          words_cleaned  \
0     [go, until, jurong, point, crazy, available, o...   
1                        [ok, lar, joking, wif, u, oni]   
2     [free, entry, in, 2, a, wkly, comp, to, win, f...   
3     [u, dun, say, so, early, hor, u, c, already, t...   
4     [nah, i, don, t, think, he, goes, to, usf, he,...   
...                                                 ...   
5567  [this, is, the, 2nd, time, we, have, tried, 2,...   
5568          [will, b, going, to, esplanade, fr, home]   
5569  [pity, was, in, mood, for, that, so, any, othe...   
5570  [the, guy, did, some, bitching, but, i, acted,...   
5571                   [rofl, its, true, to, its, name]   

                                                  text2  
0     Todays Voda numbers ending 1225 are selected t...  
1          If you have a match please call 087123002...  
2     todays voda numbers ending selected receive aw...  
3                                                   NaN  
4                                                   NaN  
...                                                 ...  
5567                                                NaN  
5568                                                NaN  
5569                                                NaN  
5570                                                NaN  
5571                                                NaN  

[5572 rows x 5 columns]

In [59]:
# Use labelEncoder method to convert class target
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

le.fit_transform(data['text'].astype(str))

array([1174, 3263, 1075, ..., 3418, 4063, 3558])

In [60]:
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(data['text'].astype(str))
vectorizer.get_feature_names_out()
print(X.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [61]:
vectorizer2 = CountVectorizer(analyzer='word', ngram_range=(2, 2))
X2 = vectorizer2.fit_transform(data['text'].astype(str))
vectorizer2.get_feature_names_out()

array(['00 in', '00 per', '00 sub', ..., 'zoom to', 'zouk with',
       'zyada kisi'], dtype=object)

In [62]:
print(X2.toarray())

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


In [63]:
df_bow = pd.DataFrame(X.toarray(), columns=vectorizer.get_feature_names_out())
df_bow

00  000  000pes  008704050406  0089  0121  01223585236  01223585334  \
0      0    0       0             0     0     0            0            0   
1      0    0       0             0     0     0            0            0   
2      0    0       0             0     0     0            0            0   
3      0    0       0             0     0     0            0            0   
4      0    0       0             0     0     0            0            0   
...   ..  ...     ...           ...   ...   ...          ...          ...   
5567   0    0       0             0     0     0            0            0   
5568   0    0       0             0     0     0            0            0   
5569   0    0       0             0     0     0            0            0   
5570   0    0       0             0     0     0            0            0   
5571   0    0       0             0     0     0            0            0   

      0125698789  02  ...  zebra  zed  zeros  zhong  zindgi  zoe  zogtorius  \
0              0   0  ...      0    0      0      0       0    0          0   
1              0   0  ...      0    0      0      0       0    0          0   
2              0   0  ...      0    0      0      0       0    0          0   
3              0   0  ...      0    0      0      0       0    0          0   
4              0   0  ...      0    0      0      0       0    0          0   
...          ...  ..  ...    ...  ...    ...    ...     ...  ...        ...   
5567           0   0  ...      0    0      0      0       0    0          0   
5568           0   0  ...      0    0      0      0       0    0          0   
5569           0   0  ...      0    0      0      0       0    0          0   
5570           0   0  ...      0    0      0      0       0    0          0   
5571           0   0  ...      0    0      0      0       0    0          0   

      zoom  zouk  zyada  
0        0     0      0  
1        0     0      0  
2        0     0      0  
3        0     0      0  
4        0     0      0  
...    ...   ...    ...  
5567     0     0      0  
5568     0     0      0  
5569     0     0      0  
5570     0     0      0  
5571     0     0      0  

[5572 rows x 8622 columns]

In [65]:
sorted_terms = df_bow.sum(axis=0).sort_values(ascending=False)
print("\nTop 5 terms:")
print(sorted_terms.head(5))

print("\nBottom 5 terms:")
print(sorted_terms.tail(5))


Top 5 terms:
you    2133
to     2055
the    1232
and     929
in      825
dtype: int64

Bottom 5 terms:
young          1
younger        1
youphone       1
02072069400    1
0125698789     1
dtype: int64
